/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...


It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

#include <stdio.h>
#include <limits.h>
#include "Problem045.h"

int tri(int n){
	return (n*(n+1))/2;}
int pen(int n){
	return (n*((3*n)-1))/2;}
int hex(int n){
	return n*((2*n)-1);}
int cmp_tp(int a, int b){
	int t=tri(a),p=pen(b);
	return (t>p)? 1: (t<p)?-1:0;;}
int cmp_ph(int a, int b){
	int p=pen(a),h=hex(b);
	return (p>h)? 1: (p<h)?-1:0;;}
int cmp_th(int a, int b){
	int t=tri(a),h=hex(b);
	return (t>h)? 1: (t<h)?-1:0;;}


int Problem045() {return 1;}
int Problem045_() {
	/**
	 * t*t + t = 3*p*p - p = 4*h*h - 2h
	 */

	int t=285-6,p=165,h=143;

	while(cmp_tp(t,p) || cmp_th(t,h)) {
		switch(cmp_tp(t,p)) {
			case -1:
				t++;
				break;
			case 0:
			default:
			case 1:
				break;
		}
		switch(cmp_th(t,h)) {
			case -1:
				t++;
				break;
			case 0:
			default:
			case 1:
				break;
		}


		while(cmp_ph(p,h) || cmp_tp(t,p)) {
			switch(cmp_ph(p,h)) {
				case -1:
					p++;
				case 0:
				default:
				case 1:
					break;
			}
			switch(cmp_tp(t,p)) {
				case -1:
				case 0:
				default:
					break;
				case 1:
					p++;
					break;
			}

			while(cmp_ph(p,h) || cmp_th(t,h)) {
				switch(cmp_ph(p,h)) {
					case -1:
					case 0:
					default:
						break;
					case 1:
						h++;
						break;
				}
				switch(cmp_th(t,h)) {
					case -1:
					case 0:
					default:
						break;
					case 1:
						h++;
						break;
				}
			}
		}
	}

	printf("%d",tri(t));

	return 0;
}
